[phases.setup]

nixPkgs = ['...', 'openssl', 'python3']

[phases.install]

cmds = ['bun install']

[phases.build]

cmds = ['npx prisma generate', 'bun run build']

[start]

cmd = 'npx prisma db push --accept-data-loss && next start -p $PORT'
